### Problem Statement




#####  Air pollution is among the most serious environmental problems with adverse effects on public health and the climate. The Air Quality Index (AQI) is a normalized measure of the evaluation of air quality. However, traditional AQI monitoring networks rely on expensive fixed-point sensors covering a limited number of sites. The aim of this project is to develop a machine learning model for AQI prediction based on leading pollutants such as PM2.5, PM10, NO2, SO2, CO, and O3. The goal is to develop a predictive model to predict AQI from real-time pollutant concentrations and implement the model as a web application for better accessibility.

##  AQI Prediction Model using Python
 ###  PM2.5 PM10
 ###  NO, NO2
 ###  NH3 - Ammonia
 ###  CO
 ###  So2
 ###  O3
 ###  Benzene, Toluene, Xylene

In [1]:
pip install numpy pandas matplotlib seaborn scikit-learn streamlit

Requirement already satisfied: numpy in c:\users\sathvik\lib\site-packages (1.26.2)
Requirement already satisfied: pandas in c:\users\sathvik\lib\site-packages (2.1.4)
Requirement already satisfied: matplotlib in c:\users\sathvik\lib\site-packages (3.8.2)
Requirement already satisfied: seaborn in c:\users\sathvik\lib\site-packages (0.13.1)
Requirement already satisfied: scikit-learn in c:\users\sathvik\lib\site-packages (1.3.2)
Requirement already satisfied: streamlit in c:\users\sathvik\lib\site-packages (1.42.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sathvik\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sathvik\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\sathvik\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\sathvik\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\sathvik\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sathvik\lib\site-packages (from matplotlib) (4.47.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\sathvik\lib\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\sathvik\lib\site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\sathvik\lib\site-packages (from matplotlib) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\sathvik\lib\site-packages (from matplotlib) (3.1.1)
Requirement already satisfied: scipy>=1.5.0 in c:\users\sathvik\lib\site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in c:\users\sathvik\lib\site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\sathvik\lib\site-packages (from scikit-learn) (3.2.0)
Requirement already satisfied: altair<6,>=4.0 in c:\users\sathvik\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.0.0 in c:\users\sathvik\lib\site-packages (from streamlit) (1.8.2)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\sathvik\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in c:\users\sathvik\lib\site-packages (from streamlit) (8.1.7)
Requirement already satisfied: protobuf<6,>=3.20 in c:\users\sathvik\lib\site-packages (from streamlit) (4.25.5)
Requirement already satisfied: pyarrow>=7.0 in c:\users\sathvik\lib\site-packages (from streamlit) (19.0.1)
Requirement already satisfied: requests<3,>=2.27 in c:\users\sathvik\lib\site-packages (from streamlit) (2.31.0)
Requirement already satisfied: rich<14,>=10.14.0 in c:\users\sathvik\lib\site-packages (from streamlit) (13.7.1)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\sathvik\lib\site-packages (from streamlit) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\sathvik\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\sathvik\lib\site-packages (from streamlit) (4.10.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\sathvik\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\sathvik\lib\site-packages (from streamlit) (3.1.44)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\sathvik\lib\site-packages (from streamlit) (0.9.1)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\sathvik\lib\site-packages (from streamlit) (6.4)
Requirement already satisfied: jinja2 in c:\users\sathvik\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.2)
Requirement already satisfied: jsonschema>=3.0 in c:\users\sathvik\lib\site-packages (from altair<6,>=4.0->streamlit) (4.20.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\sathvik\lib\site-packages (from altair<6,>=4.0->streamlit) (1.28.0)
Requirement already satisfied: colorama in c:\users\sathvik\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\sathvik\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: six>=1.5 in c:\users\sathvik\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sathvik\lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sathvik\lib\site-packages (from requests<3,>=2.27->streamlit) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sathvik\lib\site-packages (from requests<3,>=2.27->streamlit) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sathvik\lib\site-packages (from requests<3,>=2.27->streamlit) (2023.11.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\sathvik\lib\site-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\sathvik\lib\site-packages (from rich<14,>=10.14.0->streamlit) (2.17.2)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\sathvik\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\sathvik\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\sathvik\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\sathvik\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\sathvik\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.32.1)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\sathvik\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.16.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\sathvik\lib\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip list

Package                        Version
------------------------------ ---------------
absl-py                        2.1.0
altair                         5.5.0
anyio                          4.2.0
argon2-cffi                    23.1.0
argon2-cffi-bindings           21.2.0
arrow                          1.3.0
asttokens                      2.4.1
astunparse                     1.6.3
async-lru                      2.0.4
attrs                          23.2.0
azure-cognitiveservices-speech 1.36.0
Babel                          2.14.0
beautifulsoup4                 4.12.2
bleach                         6.1.0
blinker                        1.8.2
CacheControl                   0.14.0
cachetools                     5.5.0
category-encoders              2.6.4
certifi                        2023.11.17
cffi                           1.16.0
charset-normalizer             3.3.2
click                          8.1.7
cloudpickle                    3.1.0
colorama                       0.4.6
comm                           0.2.1
contourpy                      1.2.0
cryptography                   43.0.3
cv                             1.0.0
cvlib                          0.2.7
cycler                         0.12.1
Cython                         3.0.11
debugpy                        1.8.0
decorator                      5.1.1
defusedxml                     0.7.1
distlib                        0.3.9
dm-tree                        0.1.8
et-xmlfile                     1.1.0
executing                      2.0.1
Farama-Notifications           0.0.4
fastjsonschema                 2.19.1
filelock                       3.16.1
firebase-admin                 6.5.0
Flask                          3.0.3
flatbuffers                    24.3.7
fonttools                      4.47.0
fqdn                           1.5.1
fsspec                         2024.12.0
gast                           0.5.4
gekko                          1.2.1
gitdb                          4.0.12
GitPython                      3.1.44
google-api-core                2.21.0
google-api-python-client       2.149.0
google-auth                    2.35.0
google-auth-httplib2           0.2.0
google-cloud-core              2.4.1
google-cloud-firestore         2.19.0
google-cloud-storage           2.18.2
google-crc32c                  1.6.0
google-pasta                   0.2.0
google-resumable-media         2.7.2
googleapis-common-protos       1.65.0
grpcio                         1.67.0
grpcio-status                  1.67.0
gym                            0.26.2
gym-notices                    0.0.8
gymnasium                      1.0.0
h5py                           3.10.0
httplib2                       0.22.0
idna                           3.6
imageio                        2.35.1
imageio-ffmpeg                 0.6.0
imbalanced-learn               0.12.3
imblearn                       0.0
imutils                        0.5.4
ipykernel                      6.28.0
ipython                        8.19.0
ipywidgets                     8.1.3
isoduration                    20.11.0
itsdangerous                   2.2.0
jax                            0.5.0
jaxlib                         0.5.0
jedi                           0.19.1
Jinja2                         3.1.2
joblib                         1.3.2
json5                          0.9.14
jsonpointer                    2.4
jsonschema                     4.20.0
jsonschema-specifications      2023.12.1
jupyter                        1.0.0
jupyter_client                 8.6.0
jupyter-console                6.6.3
jupyter_core                   5.7.0
jupyter-events                 0.9.0
jupyter-lsp                    2.2.1
jupyter_server                 2.12.2
jupyter_server_terminals       0.5.1
jupyterlab                     4.0.10
jupyterlab_pygments            0.3.0
jupyterlab_server              2.25.2
jupyterlab_widgets             3.0.11
kaggle                         1.6.17
kagglehub                      0.3.9
keras                          3.0.5
kiwisolver                     1.4.5
libclang                       16.0.6
lxml                           5.3.0
Markdown                       3.5.2
markdown-it-py                 3.0.0
MarkupSafe                     2.1.3
matplotlib                     3.8.2
matplotlib-inline              0.1.6
mdurl                          0.1.2
media                          0.1.6
mediapipe                      0.10.21
mistune                        3.0.2
ml_dtypes                      0.5.1
moviepy                        2.1.2
mpmath                         1.3.0
msgpack                        1.1.0
namex                          0.0.7
narwhals                       1.28.0
nbclient                       0.9.0
nbconvert                      7.14.0
nbformat                       5.9.2
nest-asyncio                   1.5.8
networkx                       3.4.2
nltk                           3.9.1
notebook                       7.0.6
notebook_shim                  0.2.3
numpy                          1.26.2
openai-gym                     0.1.0
opencv-contrib-python          4.11.0.86
opencv-python                  4.9.0.80
openpyxl                       3.1.2
opt-einsum                     3.3.0
overrides                      7.4.0
packaging                      23.2
pandas                         2.1.4
pandocfilters                  1.5.0
parso                          0.8.3
patsy                          1.0.1
Pillow                         10.1.0
pip                            25.0.1
pipe                           2.1
platformdirs                   4.1.0
plotly                         5.24.1
proglog                        0.1.10
progressbar                    2.5
prometheus-client              0.19.0
prompt-toolkit                 3.0.43
proto-plus                     1.25.0
protobuf                       4.25.5
psutil                         5.9.7
pure-eval                      0.2.2
pyarrow                        19.0.1
pyasn1                         0.6.1
pyasn1_modules                 0.4.1
pycparser                      2.21
pydeck                         0.9.1
pyforest                       1.1.0
pygame                         2.6.1
Pygments                       2.17.2
PyJWT                          2.9.0
pyparsing                      3.1.1
PyPDF2                         3.0.1
pyserial                       3.5
python-dateutil                2.8.2
python-docx                    1.1.2
python-dotenv                  1.0.1
python-json-logger             2.0.7
python-slugify                 8.0.4
pytz                           2023.3.post1
pywin32                        306
pywinpty                       2.0.12
PyYAML                         6.0.1
pyzmq                          25.1.2
qtconsole                      5.5.2
QtPy                           2.4.1
referencing                    0.32.1
regex                          2024.11.6
requests                       2.31.0
rfc3339-validator              0.1.4
rfc3986-validator              0.1.1
rich                           13.7.1
rpds-py                        0.16.2
rsa                            4.9
scikit-learn                   1.3.2
scipy                          1.11.4
seaborn                        0.13.1
Send2Trash                     1.8.2
sentencepiece                  0.2.0
setuptools                     69.2.0
six                            1.16.0
smmap                          5.0.2
sniffio                        1.3.0
sounddevice                    0.5.1
soupsieve                      2.5
stable_baselines3              2.4.0
stack-data                     0.6.3
statsmodels                    0.14.4
streamlit                      1.42.2
sympy                          1.13.1
tenacity                       9.0.0
tensorboard                    2.16.2
tensorboard-data-server        0.7.2
tensorflow                     2.16.1
tensorflow-intel               2.16.1
termcolor                      2.4.0
terminado                      0.18.0
text-unidecode                 1.3
threadpoolctl                  3.2.0
tinycss2                       1.2.1
toml                           0.10.2
torch                          2.5.1
tornado                        6.4
tqdm                           4.67.1
traitlets                      5.14.1
types-python-dateutil          2.8.19.20240106
typing_extensions              4.10.0
tzdata                         2023.3
uri-template                   1.3.0
uritemplate                    4.1.1
urllib3                        2.1.0
virtualenv                     20.29.2
virtualenvwrapper-win          1.2.7
watchdog                       6.0.0
wcwidth                        0.2.13
webcolors                      1.13
webencodings                   0.5.1
websocket-client               1.7.0
Werkzeug                       3.0.1
wheel                          0.43.0
widgetsnbextension             4.0.11
wrapt                          1.16.0
xgboost                        2.1.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
# importing necessaries libraries 

import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
from warnings import filterwarnings
filterwarnings('ignore')

In [4]:
# Load Dataset
df = pd.read_csv(r'air quality data.csv')
df

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29526,Visakhapatnam,2020-06-27,15.02,50.94,7.68,25.06,19.54,12.47,0.47,8.55,23.30,2.24,12.07,0.73,41.0,Good
29527,Visakhapatnam,2020-06-28,24.38,74.09,3.42,26.06,16.53,11.99,0.52,12.72,30.14,0.74,2.21,0.38,70.0,Satisfactory
29528,Visakhapatnam,2020-06-29,22.91,65.73,3.45,29.53,18.33,10.71,0.48,8.42,30.96,0.01,0.01,0.00,68.0,Satisfactory
29529,Visakhapatnam,2020-06-30,16.64,49.97,4.05,29.26,18.80,10.03,0.52,9.84,28.30,0.00,0.00,0.00,54.0,Satisfactory
29530,Visakhapatnam,2020-07-01,15.00,66.00,0.40,26.85,14.05,5.20,0.59,2.10,17.05,NaN,NaN,NaN,50.0,Good

In [5]:
#first 5 rows
df.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  object
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: float64(13), object(3)
memory usage: 3.6+ MB

In [7]:
df.describe()

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI
count,24933.000000,18391.000000,25949.000000,25946.000000,25346.000000,19203.000000,27472.000000,25677.000000,25509.000000,23908.000000,21490.000000,11422.000000,24850.000000
mean,67.450578,118.127103,17.574730,28.560659,32.309123,23.483476,2.248598,14.531977,34.491430,3.280840,8.700972,3.070128,166.463581
std,64.661449,90.605110,22.785846,24.474746,31.646011,25.684275,6.962884,18.133775,21.694928,15.811136,19.969164,6.323247,140.696585
min,0.040000,0.010000,0.020000,0.010000,0.000000,0.010000,0.000000,0.010000,0.010000,0.000000,0.000000,0.000000,13.000000
25%,28.820000,56.255000,5.630000,11.750000,12.820000,8.580000,0.510000,5.670000,18.860000,0.120000,0.600000,0.140000,81.000000
50%,48.570000,95.680000,9.890000,21.690000,23.520000,15.850000,0.890000,9.160000,30.840000,1.070000,2.970000,0.980000,118.000000
75%,80.590000,149.745000,19.950000,37.620000,40.127500,30.020000,1.450000,15.220000,45.570000,3.080000,9.150000,3.350000,208.000000
max,949.990000,1000.000000,390.680000,362.210000,467.630000,352.890000,175.810000,193.860000,257.730000,455.030000,454.850000,170.370000,2049.000000

In [8]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
29526    False
29527    False
29528    False
29529    False
29530    False
Length: 29531, dtype: bool

In [9]:
# null values
df.isnull()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,False,False,True,True,False,False,False,True,False,False,False,False,False,False,True,True
1,False,False,True,True,False,False,False,True,False,False,False,False,False,False,True,True
2,False,False,True,True,False,False,False,True,False,False,False,False,False,False,True,True
3,False,False,True,True,False,False,False,True,False,False,False,False,False,False,True,True
4,False,False,True,True,False,False,False,True,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29526,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29527,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29528,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29529,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29530,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False,False

In [10]:
#complete null values
df.isnull().sum()

City              0
Date              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

In [11]:
# Drop rows where AQI is missing
df.dropna(subset=['AQI'], inplace=True)

In [12]:
# arranging null values in order
df.isnull().sum().sort_values(ascending=False)

Xylene        15372
PM10           7086
NH3            6536
Toluene        5826
Benzene        3535
NOx            1857
O3              807
PM2.5           678
SO2             605
CO              445
NO2             391
NO              387
City              0
Date              0
AQI               0
AQI_Bucket        0
dtype: int64

In [13]:
#shape of dataset
df.shape

(24850, 16)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24850 entries, 28 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        24850 non-null  object
 1   Date        24850 non-null  object
 2   PM2.5       24172 non-null  float64
 3   PM10        17764 non-null  float64
 4   NO          24463 non-null  float64
 5   NO2         24459 non-null  float64
 6   NOx         22993 non-null  float64
 7   NH3         18314 non-null  float64
 8   CO          24405 non-null  float64
 9   SO2         24245 non-null  float64
 10  O3          24043 non-null  float64
 11  Benzene     21315 non-null  float64
 12  Toluene     19024 non-null  float64
 13  Xylene      9478 non-null   float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: float64(13), object(3)
memory usage: 3.2+ MB

In [15]:
#stats of the dataset
df.describe()

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI
count,24172.000000,17764.000000,24463.000000,24459.000000,22993.000000,18314.000000,24405.000000,24245.000000,24043.000000,21315.000000,19024.000000,9478.000000,24850.000000
mean,67.476613,118.454435,17.622421,28.978391,32.289012,23.848366,2.345267,14.362933,34.912885,3.458668,9.525714,3.588683,166.463581
std,63.075398,89.487976,22.421138,24.627054,30.712855,25.875981,7.075208,17.428693,21.724525,16.036020,20.881085,6.754324,140.696585
min,0.040000,0.030000,0.030000,0.010000,0.000000,0.010000,0.000000,0.010000,0.010000,0.000000,0.000000,0.000000,13.000000
25%,29.000000,56.777500,5.660000,11.940000,13.110000,8.960000,0.590000,5.730000,19.250000,0.230000,1.027500,0.390000,81.000000
50%,48.785000,96.180000,9.910000,22.100000,23.680000,16.310000,0.930000,9.220000,31.250000,1.290000,3.575000,1.420000,118.000000
75%,80.925000,150.182500,20.030000,38.240000,40.170000,30.360000,1.480000,15.140000,46.080000,3.340000,10.180000,4.120000,208.000000
max,914.940000,917.080000,390.680000,362.210000,378.240000,352.890000,175.810000,186.080000,257.730000,455.030000,454.850000,170.370000,2049.000000

In [16]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
PM2.5,24172.0,67.476613,63.075398,0.04,29.0000,48.785,80.9250,914.94
PM10,17764.0,118.454435,89.487976,0.03,56.7775,96.180,150.1825,917.08
NO,24463.0,17.622421,22.421138,0.03,5.6600,9.910,20.0300,390.68
NO2,24459.0,28.978391,24.627054,0.01,11.9400,22.100,38.2400,362.21
NOx,22993.0,32.289012,30.712855,0.00,13.1100,23.680,40.1700,378.24
NH3,18314.0,23.848366,25.875981,0.01,8.9600,16.310,30.3600,352.89
CO,24405.0,2.345267,7.075208,0.00,0.5900,0.930,1.4800,175.81
SO2,24245.0,14.362933,17.428693,0.01,5.7300,9.220,15.1400,186.08
O3,24043.0,34.912885,21.724525,0.01,19.2500,31.250,46.0800,257.73
Benzene,21315.0,3.458668,16.036020,0.00,0.2300,1.290,3.3400,455.03
Toluene,19024.0,9.525714,20.881085,0.00,1.0275,3.575,10.1800,454.85
Xylene,9478.0,3.588683,6.754324,0.00,0.3900,1.420,4.1200,170.37
AQI,24850.0,166.463581,140.696585,13.00,81.0000,118.000,208.0000,2049.00

In [17]:
#percentage ofnull values in dataset
null_values_percentages=(df.isnull().sum()/df.isnull().count()*100).sort_values(ascending=False)
null_values_percentages

Xylene        61.859155
PM10          28.515091
NH3           26.301811
Toluene       23.444668
Benzene       14.225352
NOx            7.472837
O3             3.247485
PM2.5          2.728370
SO2            2.434608
CO             1.790744
NO2            1.573441
NO             1.557344
City           0.000000
Date           0.000000
AQI            0.000000
AQI_Bucket     0.000000
dtype: float64

 ## key considerations 
   ### Xylene has the highest percentage of missing values - 61.86%
   ### PM10 and NH3 28 - 26 %

In [19]:
from sklearn.impute import KNNImputer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
# KNN Imputation for missing values
imputer = KNNImputer(n_neighbors=5)
df.iloc[:, 2:-2] = imputer.fit_transform(df.iloc[:, 2:-2])

In [20]:
# Splitting Data
X = df[['PM2.5', 'PM10', 'NO', 'NO2', 'NH3', 'CO', 'SO2', 'O3', 'Benzene', 'Toluene', 'Xylene']]
y = df['AQI']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
# Train Model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [22]:
# Predictions
y_pred = model.predict(X_test)

In [23]:
# Evaluate
st.write("MAE:", mean_absolute_error(y_test, y_pred))
st.write("RMSE:", mean_squared_error(y_test, y_pred, squared=False))
st.write("R² Score:", r2_score(y_test, y_pred))

2025-02-24 22:29:41.106 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.805
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\SATHVIK\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2025-02-24 22:29:42.809 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.813 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.817 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.822 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.825 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.827 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.831 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.835 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.843 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.848 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [24]:

# Streamlit UI
st.title("AQI Prediction App")
st.write("Upload an air quality dataset to predict AQI")
uploaded_file = st.file_uploader("Upload CSV", type=["csv"])

if uploaded_file is not None:
    new_data = pd.read_csv(uploaded_file)
    predictions = model.predict(new_data)
    st.write(predictions)

2025-02-24 22:29:42.905 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.907 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.908 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.912 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.914 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.915 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.919 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.920 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.921 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.922 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:29:42.923 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [25]:
import streamlit as st
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

st.title("AQI Prediction Model")

uploaded_file = st.file_uploader("Upload Air Quality Dataset", type=["csv"])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    st.write("Dataset Preview:", df.head())

    # Define features and target variable
    X = df[['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3']]
    y = df['AQI']

    # Train Model
    model = LinearRegression()
    model.fit(X, y)

    # User Input
    st.subheader("Enter Pollutant Values:")
    pm25 = st.number_input("PM2.5", value=50.0)
    pm10 = st.number_input("PM10", value=80.0)
    no2 = st.number_input("NO2", value=20.0)
    so2 = st.number_input("SO2", value=10.0)
    co = st.number_input("CO", value=1.0)
    o3 = st.number_input("O3", value=30.0)

    # Make Prediction
    input_data = np.array([[pm25, pm10, no2, so2, co, o3]])
    predicted_aqi = model.predict(input_data)[0]

    st.subheader(f"Predicted AQI: {predicted_aqi:.2f}")

2025-02-24 22:32:12.030 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:32:12.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:32:12.033 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:32:12.035 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:32:12.035 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:32:12.038 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-24 22:32:12.039 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.